# versión de la API de kubernetes para deployments
# tipo y nombre del recurso
apiVersion: apps/v1
kind: Deployment
metadata:
  name: codercommerce-deploy
# especificaciones del despliegue (cantidad y selector de pods, la plantilla base del contenedor y los puertos)
spec:
  replicas: 5
  selector:
    matchLabels:
      app: codercommerce
  template:
    metadata:
      labels:
        app: codercommerce
    spec:
      containers:
        - name: codercommerce
          image: ignacioborraz/codercommerce:1.0.0
          ports:
            - containerPort: 9000
---
# versión de la API de kubernetes para service
# tipo y nombre del recurso
apiVersion: v1
kind: Service
metadata:
  name: codercommerce-service
# especificaciones del servicio (tipo, selector y los puertos)
spec:
  type: NodePort
  selector:
    app: codercommerce
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 30003